[tool.cibuildwheel]
build = [
    "cp37-*",
    "cp38-*",
    "cp39-*",
    "cp310-*",
    "cp311-*",
]
test-command = "pytest {project}/tests"
test-requires = ["-r", "requirements-test.txt"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
skip = ["*-musllinux_*"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "universal2"]
